### ISSUE TITLE
Ошибка сборки LibstdС++ Проход 1

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#130]
[build.log](https://github.com/Linux4Yourself/Linux4Yourself.Book/files/6411956/build.log)

**Comment by avmaisak** [comment]
![image](https://user-images.githubusercontent.com/1219921/116822446-79f58400-ab87-11eb-8324-73d924c632f2.png)

**Comment by avmaisak** [comment]
[build.log](https://github.com/Linux4Yourself/Linux4Yourself.Book/files/6411967/build.log)

**Comment by avmaisak** [comment]
при повторной сборке с самого начала, ошибка исчезла, но появилась #133 .

**Comment by makpif** [comment]
при повторной сборке с моим костылем или без?

**Comment by avmaisak** [comment]
> при повторной сборке с моим костылем или без?

без костыля

**Comment by makpif** [comment]
тогда хорошо

**Comment by makpif** [comment]
у меня тоже более жтой ошибки нет
думаю иссуе можно закрыть
