### ISSUE TITLE
Ошибка Ncurses multilib на этапе configure

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#134]
вероятно связано с #130 

``
checking $CFLAGS variable... ok
checking $CC variable... broken
configure: WARNING: your environment uses the CC variable to hold CFLAGS/CPPFLAGS options
checking how to run the C preprocessor... /lib/cpp
configure: error: C preprocessor "/lib/cpp" fails sanity check

``

**Comment by makpif** [comment]
нет, с #130 не связанно.
она ачемто лезет к /lib/cpp

**Comment by makpif** [comment]
если вы пропутили этап установки glibc 32 (#133) то этот этап не выполниться

**Comment by makpif** [comment]
не воспроизвелось
