### ISSUE TITLE
дополнить про legacy-boot и MBR

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#16]

**Comment by makpif** [comment]
но я это сделать не могу т.к. использую UEFI

**Comment by Linuxoid85** [comment]
Ох... Там всё просто, даже не вижу смысла что-то писать. На GPT создать раздел 1М без ФС, тип Bios Boot. А на MBR вообще ничего не надо. Только корень и своп.
