### ISSUE TITLE
Сохранять исходники в /usr/src вместо /sources

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#169]

**Comment by Linuxoid85** [comment]
Я думаю, это нужно сделать после сборки временной системы. Либо же, после того, как базовая система собрана и предоставляются пакеты с дополнительными программами типа иксов, WM, DE и прочего.

**Comment by makpif** [comment]
прчем тут это
в подготовке создаеться каталог /source, а предлагаеться использоваь вместо него usr/src

**Comment by avmaisak** [comment]
я просто поменял в заголовке на правильное название каталога (sources) а не source
