### ISSUE TITLE
загрузка патчей через браузер

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book#213]
пр нажатии на ссылку кидает на страницу с содержимым патча, а не загружает его

**Comment by Linuxoid85** [comment]
Понятное дело. Это же текстовый файл, а его браузер именно открывает. Патч нужно в архив закатать, а после скачивания распаковать и применить. Но лучше, конечно, качать всё из книги с помощью wget))).

**Comment by makpif** [comment]
да но в лфс все норм качает

**Comment by avmaisak** [comment]
это проблема? или идти копаться в настройках nginx?

**Comment by makpif** [comment]
всмысле? это да, мешает. И кстати патчи у нас вроде не с сервера, а с raw.githubcontentsчто-то там

**Comment by avmaisak** [comment]
уже нет )

**Comment by avmaisak** [comment]
кстати проверь-ка ,

https://lx4u.ru/downloads/packages/bzip2-1.0.8-install_docs-1.patch
https://lx4u.ru/downloads/packages/coreutils-8.32-i18n-1.patch
https://lx4u.ru/downloads/packages/glibc-2.33-fhs-1.patch
https://lx4u.ru/downloads/packages/kbd-2.4.0-backspace-1.patch
https://lx4u.ru/downloads/packages/sysvinit-2.99-consolidated-1.patch
https://lx4u.ru/downloads/packages/efivar-37-gcc_9-1.patch

они нормально открываются, как нужно.

**Comment by makpif** [comment]
ага, все норм
