### ISSUE TITLE
не отображается sbu2

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book#242]

**Comment by avmaisak** [comment]
в core-packages - должно быть указано значение sbu2. Тогда, если указать ``<package-info :package="package" showsbu2></package-info>`` - будет отображаться. Нужно проверить. Так что пока issue открыто.

**Comment by avmaisak** [comment]
ну как?

**Comment by makpif** [comment]
нет

**Comment by makpif** [comment]
sbu2 заполнен

**Comment by avmaisak** [comment]
на каком пакете можно проверить?

**Comment by makpif** [comment]
я всегда все на glibc проверяю (в моей ОС), а так на любом
