### ISSUE TITLE
[IDEA]  перенести скрипты пакетов в репозиторий Scripts

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#248]
- Предлагаю рассмотреть вариант переноса скриптов пакетов в репозиторий ``scripts``. 

И создать в нем следующую структуру: (например)

base/binutils

И разбить на несколько файлов. и уже их задействовать в книге.

- prepare
- configure
- build.sh
- install

- prepare_x86
- configure_x86
- build_x86
- install_x86

Таким образом, я смогу автоматизировать сборку основной системы, для тестирования.

**Comment by avmaisak** [comment]
я смогу подготовить структуру параллельно основной работе, а потом выполнить плавный перенос.

**Comment by avmaisak** [comment]
https://github.com/Linux4Yourself/Linux4Yourself.Book.Scripts/tree/feature/base/src/base

**Comment by makpif** [comment]
я пока буду нормально писать пока, так задолбаться можно 15 файлов н 1 пакет

**Comment by makpif** [comment]
хотя 1-2 файлами не выйдет - их ж в книге надо подключать

**Comment by Linuxoid85** [comment]
Подключать в книге - можно, но в некоторых случаях писанины будет больше, чем в тех файлах 😁️. Если я правильно понял идею - вы создаёте в отдельном репозитории скрипты, а потом их подключаете в книге.

Я не думаю, что это прям-таки хорошая идея. Это пригодится только тогда, когда набор команд действительно большой (как, например, в скрипте [`version-check.sh`](https://lx4u.ru/dev/#/prepare/requrements). Либо же последовательность команд при компиляции gcc, там тоже много всего. Но для остального - не нужно. В каких-то мелких пакетах вы з@ебётесь подключать эти файлы :)

Однако, это может пригодиться при написании своего ПМ или утилиты для автоматизированной установки и удаления пакетов. В частности, сборки их из исходных кодов. Вот здесь я ЗА.

**Comment by makpif** [comment]
антон как раз автаматизацию пишет

пример использования
https://github.com/Linux4Yourself/Linux4Yourself.Book/blob/develop/docs/build-system/mpc.md

я когда начал с этим разбирать ся вначале запутался не много, но если все по шаблонам делать, просто файлы копируя то норм.

тем более значительную часть делает tools/gen-core.js
