### ISSUE TITLE
Сгенерить changelog (как страницу книги)

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book#264]
и он по идее должен включать инфу о комитах из script и packages

**Comment by avmaisak** [comment]
генерить можно из истории комитов. Но комиты должны быть аккуратные, а не как сейчас

**Comment by makpif** [comment]
да, после релиза 1.0 надо будет для dev версии их нормально обзывать

**Comment by makpif** [comment]
пока чейнджлог не нужен, но потом будет крайне полезная для пользователей dev версии вещь

**Comment by avmaisak** [comment]
Боюсь  что придется его формировать вручную.
