### ISSUE TITLE
Удобная навигация по страницам

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/Linux4Yourself.Book#277]
Добавить к КАЖДОЙ странице кнопки "Предыдущая" и "Следующая" с ссылками на предыдущую и следующую страницы руководства, дабы упростить навигацию по книге (особенно актуально для мобилок, где, чтобы переключиться на нужную страницу, необходимо залезать в боковое меню). Помимо этого, кнопки "Вверх" (к содержанию текущей главы) и "Содержание" (для открытия оглавления всей книги). На Markdown писать всё это к каждой странице - запарно, на js (и потом вставлять в страницу, как это сделано с информацией о пакете) - вполне себе можно, думаю. Но жабаскрипт для меня - китайская грамота, пардон.

**Comment by makpif** [comment]
тоже об этом думал
