### ISSUE TITLE
Ошибка отображения картинок

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#299]
Нарушены пути.

**Comment by Linuxoid85** [comment]
Решил здесь: https://github.com/Linux4Yourself/Linux4Yourself.Book/tree/Linuxoid85-patch-1/docs/additional/pic

**Comment by Linuxoid85** [comment]
И здесь: https://github.com/Linux4Yourself/Linux4Yourself.Book/pull/306
