### ISSUE TITLE
/usr/sbin - создать ссылку на /usr/bin

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book#308]
последнее время у меня от этого sbin отдельного только проблемы, а толку ноль, уверен что большинство имеют его в патч обычного юзера

**Comment by Linuxoid85** [comment]
Вот тут уже ХЗ. У меня всегда /bin, /sbin, /usr/bin, /usr/sbin были именно такими, какими должны быть, и проблем не замечал. Да и я обеими руками за классическое расположение директорий. Хотя, если делать ссылки /usr/bin и /usr/sbin, не придётся при компиляции ПО некоторые файлы перемещать из /usr/{bin,sbin} в корень. Как, например, bash. Ну и другие.

**Comment by makpif** [comment]
про корень есть с самого начала, сейчас /bin /lib /sbin и в лфс линки на юзр и в 90% дистров
я предлагаю еще и /usr/sbin с /usr/bin совместить

**Comment by avmaisak** [comment]
Я не против, если это ничего не заломает
