### ISSUE TITLE
Выбор текстового редактора

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#336]
- Vim
- Nano
- Emacs
- micro

**Comment by Linuxoid85** [comment]
Так как LX4Y - система НЕ для новичков, то nano отбрасываем. Он очень неудобный - неудобные сочетания клавиш, отсутствие переноса текста (или же я не нашёл) и много других недостатков.

А вот vim/emacs уже намного понятнее и функциональнее. И удобнее. Лично я предпочитаю vim. Как познакомился с ним в 2011, так и использую. emacs тоже хорош, даже очень. Комбайн какой-то)).

Лично я предлагаю пользователям выбирать - vim или emacs. А если хочет чего попроще, то не лучше выкинуть nano и выбрать тот же micro? Минималистичный, простой, удобный... То, что действительно неплохо для *обычного* пользователя.

**Comment by makpif** [comment]
думаю vim т.к. против nano уже высказались, ну список зависимостей емакс вызывает сомнения, хотя большинство и можно отключить, но думаю рекомендуються в блфс они не с проста
https://www.linuxfromscratch.org/blfs/view/systemd/postlfs/emacs.html

**Comment by avmaisak** [comment]
Что ж вы все так против nano? ))

**Comment by makpif** [comment]
я нет, мне все равно

**Comment by makpif** [comment]
я сказал что уже есть те кто против него и все

**Comment by avmaisak** [comment]
Пока текстовые редакторы не добавили - issue в открытом состоянии

**Comment by Linuxoid85** [comment]
Лично я за то, чтобы предоставить пользователю выбор. Это или micro (для тех, кому нужен самый обычный текстовый редактор), или vim/emacs (которым нужно что-то более продвинутое).
