### ISSUE TITLE
Описание multilib

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#378]
Не везде, в меню можно увидеть multilib. Приходится пролиствать.
в пакете ncurses - вообще не отобразился заголовок.

Надо по всем пакетам пробежаться, и посмотреть

**Comment by makpif** [comment]
в каком меню?

**Comment by makpif** [comment]
в нкурсес <warn> не сработал

**Comment by makpif** [comment]
это с "warn" проблема

**Comment by makpif** [comment]
почему то варн только делает текст меньше и все
