### ISSUE TITLE
Отдельные "Доп. материалы"

### ISSUE THREAD

**Issue by Linuxoid85** [Linux4Yourself/Linux4Yourself.Book#390]
Сейчас столкнулся с ситуацией. Для extra репа нужно было одну статью закинуть, где ссылка на дополнительные материалы. А куда их? Можно, конечно, создать ещё одни у extra-книги, можно в обычную заливать, но лучше-таки сделать отдельный реп с дополнительными материалами, ИМХО.

**Comment by avmaisak** [comment]
Давай пока в обычную
