### ISSUE TITLE
Gmp - multilib - warnings

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#424]
Проверить

![image](https://user-images.githubusercontent.com/1219921/120019355-07928b00-bff1-11eb-82af-90a5a409c02d.png)

**Comment by makpif** [comment]
стандартный варнинг связанный с устаревшими .la файлами

**Comment by avmaisak** [comment]
может в инструкция по сборке указать на то, что могут быть такие варнинги?

**Comment by makpif** [comment]
варнинги всякие могут быть

при компиляции они сотнями лезут. лучше в начале написать что все варнинги можно игнорить
