### ISSUE TITLE
Gcc работоспособность

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#426]
В lx4u странный результат при проверке работоспособности
Причем проверки LFS отрабатывают корректно

![image](https://user-images.githubusercontent.com/1219921/120045684-40465a80-c019-11eb-8a72-f8a35d2f8373.png)

**Comment by makpif** [comment]
странно

**Comment by avmaisak** [comment]
> странно

Причем пакет работоспособный, даже тесты

**Comment by makpif** [comment]
выполни
mkdir tmp
echo 'int main(){}' > dummy.c
cc dummy.c
ls 

какие файлы получаться?

**Comment by avmaisak** [comment]
файл a.out есть

**Comment by makpif** [comment]
readelf -l a.out | grep ': /lib'

что говорит?

**Comment by makpif** [comment]
ща исправлю
