### ISSUE TITLE
Добавить коментарии о результатах тестирования

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#430]
Не все результаты тестов пакетов возвращают положительный результат. Дополнить соответствующие разделы о том, что  тесты могу провалиться

**Comment by Linuxoid85** [comment]
Потихоньку добавляю информацию (например, [здесь](https://github.com/Linux4Yourself/Linux4Yourself.Book/pull/540)). Ко времени релиза, думаю, управлюсь. Если не надо - отклоняйте )).

**Comment by Linuxoid85** [comment]
Не думаю, что очень хорошим будет оставлять это на будущее.

**Comment by avmaisak** [comment]
++

**Comment by makpif** [comment]
вроде все?
