### ISSUE TITLE
find utils

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#449]
Ошибка при тестировании. Не соответствует результатам LFS

![image](https://user-images.githubusercontent.com/1219921/120107758-e5247d00-c16a-11eb-90e1-c6df102c115a.png)

![image](https://user-images.githubusercontent.com/1219921/120107780-f4a3c600-c16a-11eb-92e9-a30779664ea4.png)

**Comment by makpif** [comment]
у меня не воспроизвелось

мб из за того что я отклонился где то конечно, хотя хз.

мб рандом

**Comment by avmaisak** [comment]
какой смысл в тестировании, если отклоняться от того, что необходимо проверить ?

**Comment by makpif** [comment]
я собираю себе основную ОС

а тестирование для меня - цель второстепенная

**Comment by makpif** [comment]
думаю можно закрыть - у меня не воспроизвелось, мб рандом ошибка
