### ISSUE TITLE
Измерение SBU

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#489]
https://www.linuxfromscratch.org/~bdubbs/about.html

**Comment by makpif** [comment]
я засекал только make

ну и у нас сбу может быть чут другим

**Comment by avmaisak** [comment]
Добавить информацию о том, как измерить

**Comment by Linuxoid85** [comment]
https://github.com/Linux4Yourself/Linux4Yourself.Book/pull/490

Сейчас надо? Просто в Milestone поставлено `Future`...

**Comment by makpif** [comment]
future значит что к 1.0 необязательно
