### ISSUE TITLE
make-ca

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#497]
Предлагаю все таки включить, чтобы юзер испытывал меньше боли и конечная система была боле менее пригодной для элементарных действий, без раздражения.

_Originally posted by @avmaisak in https://github.com/Linux4Yourself/Linux4Yourself.Book/discussions/496_

**Comment by makpif** [comment]
тогда надо еще p11-kit и libtasn

**Comment by avmaisak** [comment]
да
