### ISSUE TITLE
Делаем систему загрузочной - сломали навигацию

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#526]
![image](https://user-images.githubusercontent.com/1219921/121421160-89ca6a00-c976-11eb-83ed-84459205c159.png)

**Comment by Linuxoid85** [comment]
Потому что файл переместили. Кстати, [здесь](https://github.com/Linux4Yourself/Linux4Yourself.Book/pull/529) исправлено.
