### ISSUE TITLE
пресс-релиз

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book#580]

**Comment by avmaisak** [comment]
https://docs.google.com/document/d/1LAskRuTyUA5Tt7y8LwficpboNZWWSX2Y1EPXPO7adnY/edit

Предлагаю в этом комментарии, поставить "пальцы", когда документ будет утверждён всеми активными участниками проекта.

**Comment by makpif** [comment]
ссылку мб добавить надо?

**Comment by avmaisak** [comment]
Ссылки на google docs недостаточно?

**Comment by makpif** [comment]
в документ ссылку на книгу и гитхаб

**Comment by avmaisak** [comment]
А ты про это. Тут надо думать как правильно поступить. Возможно имеет смысл добавить что то типа новостного раздела. А пока - я думал предмет этого issue согласование текста, не более того.

**Comment by Linuxoid85** [comment]
Думаю, можно закрывать. Конечно, осталось дождаться момента, когда на ЛОРе переместят в обычные новости из неподтвержденных, но я думаю, что завтра это будет готово. К тому же, с текстом пресс-релиза мы опредедились.
