### ISSUE TITLE
примерное время между релизами

### ISSUE THREAD

**Issue by makpif** [Linux4Yourself/Linux4Yourself.Book#585]
думаю стоит решить, как часто мы будем выпускать новые релизы и как менять цифры в версии

понятно что релиз будет когда мы решим, но все же стоит примерный срок определить

Я предлагаю:
Где то раз в 3 месяца. Если только апдейты и маленькие правки - менять вторую цифру
Если что по больше - первую

**Comment by avmaisak** [comment]
Предлагаю на этот год примерно такой план выпуска:
https://github.com/Linux4Yourself/Linux4Yourself.Book/milestones

**Comment by Linuxoid85** [comment]
Согласен с Makpif.
Кстати. Помимо Milestone, можно выпускать промежуточные версии, в которых небольшие изменения (например, исправление ошибок, дополнение содержания и пр.).

А выпускать одни 2.0, 3.0, 4.0, 100500.0 - ну как-то не очень 😁

**Comment by Linuxoid85** [comment]
UPD. Насчёт изменений уже релизнутых версий. Я считаю, что нужно пропускать только исправление ошибок (опечаток, пунктуационных ошибок, ошибок в коммандах, которые нужно вводить). Всё остальное (изменение содержания, обновление/замена пакетов) пропускать в текущие/предыдущие релизы нельзя, это всё в будущие версии.
