### ISSUE TITLE
Wget - тесты

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#654]
Добавить тесты

SKIP: wget_cookie_fuzzer
SKIP: wget_ftpls_fuzzer
SKIP: wget_html_fuzzer
SKIP: wget_netrc_fuzzer
SKIP: wget_options_fuzzer
PASS: wget_css_fuzzer
SKIP: wget_read_hunk_fuzzer
SKIP: wget_progress_fuzzer
SKIP: wget_robots_fuzzer
SKIP: wget_url_fuzzer
SKIP: wget_ntlm_fuzzer
============================================================================
Testsuite summary for wget 1.21.1
============================================================================
# TOTAL: 11
# PASS:  1
# SKIP:  10
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/usr/src/wget-1.21.1/fuzz'
make[3]: Leaving directory '/usr/src/wget-1.21.1/fuzz'
make[2]: Leaving directory '/usr/src/wget-1.21.1/fuzz'
Making check in tests
make[2]: Entering directory '/usr/src/wget-1.21.1/tests'
make  unit-tests
make[3]: Entering directory '/usr/src/wget-1.21.1/tests'
cd ../src && make  libunittest.a
  CC       unit-tests.o
make[4]: Entering directory '/usr/src/wget-1.21.1/src'
make[4]: Leaving directory '/usr/src/wget-1.21.1/src'
  CCLD     unit-tests
make[3]: Leaving directory '/usr/src/wget-1.21.1/tests'
make  check-TESTS
make[3]: Entering directory '/usr/src/wget-1.21.1/tests'
cd ../src && make  libunittest.a
make[4]: Entering directory '/usr/src/wget-1.21.1/src'
make[4]: Leaving directory '/usr/src/wget-1.21.1/src'
  CCLD     unit-tests
make[4]: Entering directory '/usr/src/wget-1.21.1/tests'
cd ../src && make  libunittest.a
FAIL: Test-auth-basic.px
FAIL: Test-auth-no-challenge.px
make[5]: Entering directory '/usr/src/wget-1.21.1/src'
FAIL: Test-auth-no-challenge-url.px
FAIL: Test-auth-with-content-disposition.px
FAIL: Test-auth-retcode.px
FAIL: Test-c-full.px
make[5]: Leaving directory '/usr/src/wget-1.21.1/src'
FAIL: Test-c-partial.px
FAIL: Test-c.px
FAIL: Test-c-shorter.px
FAIL: Test-cookies.px
FAIL: Test-cookies-401.px
FAIL: Test-E-k-K.px
FAIL: Test-E-k.px
FAIL: Test-ftp-bad-list.px
FAIL: Test-ftp.px
FAIL: Test-ftp-pasv-fail.px
FAIL: Test-ftp-recursive.px
SKIP: Test-ftp-iri.px
SKIP: Test-ftp-iri-fallback.px
SKIP: Test-ftp-iri-recursive.px
SKIP: Test-ftp-iri-disabled.px
FAIL: Test-ftp-list-Multinet.px
FAIL: Test-ftp-list-Unknown.px
FAIL: Test-ftp-list-Unknown-hidden.px
FAIL: Test-ftp-list-Unknown-a.px
FAIL: Test-ftp-list-Unknown-list-a-fails.px
FAIL: Test-HTTP-Content-Disposition-1.px
FAIL: Test-ftp-list-UNIX-hidden.px
FAIL: Test-HTTP-Content-Disposition-2.px
FAIL: Test-HTTP-Content-Disposition.px
FAIL: Test-ftp--start-pos.px
FAIL: Test-i-http.px
SKIP: Test-idn-headers.px
FAIL: Test-i-ftp.px
SKIP: Test-idn-cmd.px
SKIP: Test-idn-meta.px
SKIP: Test-idn-cmd-utf8.px
SKIP: Test-idn-robots-utf8.px
SKIP: Test-idn-robots.px
SKIP: Test-iri.px
FAIL: Test-iri-disabled.px
SKIP: Test-iri-percent.px
FAIL: Test-k.px
FAIL: Test-meta-robots.px
SKIP: Test-iri-forced-remote.px
FAIL: Test-N-current.px
FAIL: Test-N-HTTP-Content-Disposition.px
SKIP: Test-iri-list.px
FAIL: Test-N--no-content-disposition.px
FAIL: Test-N--no-content-disposition-trivial.px
FAIL: Test--no-content-disposition.px
FAIL: Test-N-no-info.px
FAIL: Test--no-content-disposition-trivial.px
FAIL: Test-N-old.px
FAIL: Test-nonexisting-quiet.px
FAIL: Test-noop.px
FAIL: Test-np.px
FAIL: Test-N.px
FAIL: Test-N-smaller.px
FAIL: Test-O-HTTP-Content-Disposition.px
FAIL: Test-O-nc.px
FAIL: Test-O--no-content-disposition.px
FAIL: Test-O--no-content-disposition-trivial.px
FAIL: Test-O-nonexisting.px
FAIL: Test-O.px
FAIL: Test--post-file.px
FAIL: Test-restrict-ascii.px
FAIL: Test-proxied-https-auth-keepalive.px
FAIL: Test-proxy-auth-basic.px
FAIL: Test-proxied-https-auth.px
FAIL: Test-Restrict-Lowercase.px
FAIL: Test-stdouterr.px
FAIL: Test--spider-fail.px
FAIL: Test-Restrict-Uppercase.px
FAIL: Test--spider.px
FAIL: Test--spider-r-HTTP-Content-Disposition.px
FAIL: Test--spider-r--no-content-disposition.px
FAIL: Test--spider-r--no-content-disposition-trivial.px
FAIL: Test--spider-r.px
FAIL: Test--start-pos.px
FAIL: Test--start-pos--continue.px
FAIL: Test-204.px
FAIL: Test--httpsonly-r.px
FAIL: Test-ftp-pasv-not-supported.px
FAIL: Test-https-tlsv1.px
FAIL: Test-https-pfs.px
FAIL: Test-https-selfsigned.px
FAIL: Test-https-clientcert.px
FAIL: Test-https-tlsv1x.px
  CCLD     unit-tests
FAIL: Test-https-weboftrust.px
FAIL: Test-https-crl.px
FAIL: Test-https-badcerts.px
PASS: unit-tests
============================================================================
Testsuite summary for wget 1.21.1
============================================================================
# TOTAL: 93
# PASS:  1
# SKIP:  14
# XFAIL: 0
# FAIL:  78
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to bug-wget@gnu.org
============================================================================

**Comment by makpif** [comment]
нет зависимостей для тестов
