### ISSUE TITLE
Объяснение параметров базового bashrc

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#66]
параметры разделить - каждый с новой строки. Трудно читать.

![image](https://user-images.githubusercontent.com/1219921/115972466-13ed7900-a557-11eb-92ef-ce061045cc7b.png)

**Comment by makpif** [comment]
у меня и было в моем мд разделено
а когда сюда кинул - почумуто слетело

**Comment by makpif** [comment]
вроде исправил, PR висит
