### ISSUE TITLE
Опечатки, глава "Сборка временной системы"

### ISSUE THREAD

**Issue by aburuss** [Linux4Yourself/Linux4Yourself.Book#674]
1. https://lx4u.ru/rel/1.2/#/build-temp-system/tempsystem

"Хотя пакеты и будут установлены на своё окончательное место, но их пока нельзя будет использовать, и основные инструменты будут задействованы из **хост системы**." заменить на "Хотя пакеты и будут установлены на своё окончательное место, но их пока нельзя будет использовать, и основные инструменты будут задействованы из **хост-системы**."

2. https://lx4u.ru/rel/1.2/#/build-temp-system/ncurses?id=%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0

Вместо "Во-первых, убедитесь, что gawk будет найден первым:" предлагаю "Сначала убедитесь, что gawk будет найден первым:" , так как далее по тексту нет слова "во-вторых". 

3. https://lx4u.ru/rel/1.2/#/build-temp-system/ncurses?id=%D0%97%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2

"--enable-widec - Включает установку библиотек с поддержкой **много-байтовых** символов." заменить на "--enable-widec - Включает установку библиотек с поддержкой **многобайтовых** символов."

4. https://lx4u.ru/rel/1.2/#/build-temp-system/file?id=%D0%9F%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0

"На хост-системе должна присутствовать утилита **file. вы** можете также собрать её следующим образом:" заменить на "На хост-системе должна присутствовать утилита **file. Вы** можете также собрать её следующим образом:"

5. https://lx4u.ru/rel/1.2/#/build-temp-system/make?id=%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0

"Так как мы выполняем **кросс компиляцию**, следует выставить этот параметр." заменить на "Так как мы выполняем **кросс-компиляцию**, следует выставить этот параметр."

6. https://lx4u.ru/rel/1.2/#/build-temp-system/binutils-p2?id=%D0%94%D0%BB%D1%8F-multilib

В разных главах слово "multilib" пишется по-разному - то "MuliLib", то "multilib", наверное, надо привести к одному варианту.

7. https://lx4u.ru/rel/1.2/#/build-temp-system/change-owner?id=%D0%A1%D0%BC%D0%B5%D0%BD%D0%B0-%D0%B2%D0%BB%D0%B0%D0%B4%D0%B5%D0%BB%D1%8C%D1%86%D0%B0-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3%D0%B0-lin

7.1. "Теперь, когда все циклические зависимости были разрешены, мы сможем использовать среду chroot, чтобы максимально изолироваться от **хост системы**, которая сейчас предоставляет инструменты для сборки." заменить на "Теперь, когда все циклические зависимости были разрешены, мы сможем использовать среду chroot, чтобы максимально изолироваться от **хост-системы**, которая сейчас предоставляет инструменты для сборки."

7.2. "После этих действий можно производить дальнейшие действия." предлагаю заменить на "После этого можно производить дальнейшие действия."

8. https://lx4u.ru/rel/1.2/#/build-temp-system/gettext?id=%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

"Нам **понядобятся** только следующие утилиты" на "Нам **понадобятся** только следующие утилиты"

9. https://lx4u.ru/rel/1.2/#/build-temp-system/cleanup?id=%D0%92%D1%8B%D1%85%D0%BE%D0%B4-%D0%B8%D0%B7-%D1%81%D1%80%D0%B5%D0%B4%D1%8B-chroot

Страница по ссылке не найдена.

**Comment by makpif** [comment]
> Вместо "Во-первых, убедитесь, что gawk будет найден первым:" предлагаю "Сначала убедитесь, что gawk будет найден первым:" , так как далее по тексту нет слова "во-вторых".

Просто 
Убедитесь, что gawk будет найден первым:
