### ISSUE TITLE
непонятно, в каких случаях необходимо создавать отдельный раздел для legacy boot

### ISSUE THREAD

**Issue by amadis** [Linux4Yourself/Linux4Yourself.Book#705]
дополните, пожалуйста, абзац

![изображение](https://user-images.githubusercontent.com/3416446/124936123-f0db4d00-e00e-11eb-8bd3-97ae7d0eef71.png)

**Comment by Linuxoid85** [comment]
Для Legacy или если обычный BIOS, но на харде таблица разделов GPT - тогда нужен отдельный раздел. В остальных случаях по другим инструкциям.

Здесь не очень понятно, согласен. Переделаю).
