### ISSUE TITLE
Написать Test план.

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#77]
Оформить шаблон тест плана в виде чек листа.

**Comment by makpif** [comment]
тест план всмысле для того чтоб обновы чекать?

**Comment by makpif** [comment]
или того что сделать надо в книге

**Comment by avmaisak** [comment]
Как проверить то, что написано в книге - работает ?

Нужно по идее каждый пункт самостоятельно пройти, и убедиться что все работает. Кроме как создать шаблон чек листа - не вижу альтернативы.

Прямо создать его по тем главам, где что-то происходит, вводятся команды, и ожидается результат.

**Comment by makpif** [comment]
в каком ввиде должен быть - типо файл в репе где написано
глава 84846
   шаг 1 - ок
   шаг 2 - ошибка
   шаг 3 - надо проверить

или что?

**Comment by avmaisak** [comment]
Да типа того. Разместить шаблон на странице WIKI в репозитории, и потом при тестировании создавать issue, с этим шаблоном.

**Comment by makpif** [comment]
ну не знаю
все равно плохо это понимаю
