### ISSUE TITLE
Сделать общий компонент для шапки инфо по пакету

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#88]

**Comment by makpif** [comment]
но вообще можно просто шапку копироать и все

**Comment by avmaisak** [comment]
Работа в процессе. Не  самое удачное решение выполнять копипасту одного и того же по многочисленным страницам. При изменении шапки. придется все везде заменять, к тому же можно сократить много кода, переиспользуя один компонент.
