### ISSUE TITLE
О приоритете

### ISSUE THREAD

**Issue by avmaisak** [Linux4Yourself/Linux4Yourself.Book#95]
Заменить на русские понятные определения

- required
- important
- optional

**Comment by makpif** [comment]
в о приоритете перевести легко, но нужно еще в жсоне
это можно через sed но я работаю через веб интерфейс + загружаю новые файлы
поэтому мне это достаточно проблематично сделать
необходимый
важный
не обязательный

**Comment by avmaisak** [comment]
в json-е - приоритет оставить как есть. Там не место русскоязычным наименованиям.

**Comment by makpif** [comment]
тогда получаеться что в о приоритете одни значения, а реально в книге английские

**Comment by makpif** [comment]
я считаю что в о приоритете должно быть тоже что и в книге

**Comment by avmaisak** [comment]
В пакете json - только определения. required |  important | optional. Как их использовать в других местах - уже зона ответственности другая. Например  в книге будет переопределение - required  - важно, и т.д. А например для других нужд, понадобятся англоязычные наименования.

**Comment by makpif** [comment]
тогда реализуйте то чтобы в книге они были переведенны, я не переводил потому что в книге не переведенны

**Comment by avmaisak** [comment]
все правильно. В книге все будет ок
